name: Publish

on:
  push:
    tags:
      - '*'
jobs:
  build-linux:
    name: Publish Linux Binaries
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        cmake ./
        make
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: calculator
        asset_name: linux-amd64
        tag: ${{ github.ref }}
        overwrite: true
  build-macos:
    name: Publish macOS binaries
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        cmake ./
        make
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: calculator
        asset_name: darwin-amd64
        tag: ${{ github.ref }}
        overwrite: true
  build-windows:
    name: Publish Windows binaries
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        cmake -G "Unix Makefiles" ./
        make
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: calculator.exe
        asset_name: windows-amd64.exe
        tag: ${{ github.ref }}
        overwrite: true
  build-linux-arm:
    name: Publish Linux ARM Binaries
    runs-on: buildjet-2vcpu-ubuntu-2204-arm

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        #sudo apt-get update
        #sudo apt-get upgrade cmake
        cmake ./
        make
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: calculator
        asset_name: linux-arm64
        tag: ${{ github.ref }}
        overwrite: true
