name: Publish

on:
  push:
    tags:
      - '*'
jobs:
  build-linux:
    name: Publish Linux Binaries
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        cd calculator
        g++ -o ../calc -O1 main.cpp
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: calc
        asset_name: linux-amd64
        tag: ${{ github.ref }}
        overwrite: true
  build-macos:
    name: Publish macOS binaries
    runs-on: macos-12

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        cd calculator
        g++ -o ../calc -O1 main.cpp
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: calc
        asset_name: darwin-amd64
        tag: ${{ github.ref }}
        overwrite: true
  build-windows:
    name: Publish Windows binaries
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: g++.exe -o ./calc.exe -O1 calculator/main.cpp
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: calc.exe
        asset_name: windows-amd64.exe
        tag: ${{ github.ref }}
        overwrite: true
